//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Game.Hotfix.Cfg.Item
{

public sealed partial class Entity :  Bright.Config.BeanBase 
{
    public Entity(JSONNode _json) 
    {
        { if(!_json["Id"].IsNumber) { throw new SerializationException(); }  Id = _json["Id"]; }
        { if(!_json["EntityType"].IsNumber) { throw new SerializationException(); }  EntityType = (EntityType)_json["EntityType"].AsInt; }
        { if(!_json["AssetName"].IsString) { throw new SerializationException(); }  AssetName = _json["AssetName"]; }
        PostInit();
    }

    public Entity(int Id, EntityType EntityType, string AssetName ) 
    {
        this.Id = Id;
        this.EntityType = EntityType;
        this.AssetName = AssetName;
        PostInit();
    }

    public static Entity DeserializeEntity(JSONNode _json)
    {
        return new Item.Entity(_json);
    }

    /// <summary>
    /// 实体编号
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 实体类型
    /// </summary>
    public EntityType EntityType { get; private set; }
    /// <summary>
    /// 资源名称
    /// </summary>
    public string AssetName { get; private set; }

    public const int __ID__ = -574646498;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EntityType:" + EntityType + ","
        + "AssetName:" + AssetName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
