//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Game.Hotfix.Cfg.Item
{

public sealed partial class Scene :  Bright.Config.BeanBase 
{
    public Scene(JSONNode _json) 
    {
        { if(!_json["Id"].IsNumber) { throw new SerializationException(); }  Id = _json["Id"]; }
        { if(!_json["AssetName"].IsString) { throw new SerializationException(); }  AssetName = _json["AssetName"]; }
        { if(!_json["BackgroundMusicId"].IsNumber) { throw new SerializationException(); }  BackgroundMusicId = _json["BackgroundMusicId"]; }
        PostInit();
    }

    public Scene(int Id, string AssetName, int BackgroundMusicId ) 
    {
        this.Id = Id;
        this.AssetName = AssetName;
        this.BackgroundMusicId = BackgroundMusicId;
        PostInit();
    }

    public static Scene DeserializeScene(JSONNode _json)
    {
        return new Item.Scene(_json);
    }

    /// <summary>
    /// 实体编号
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 资源名称
    /// </summary>
    public string AssetName { get; private set; }
    /// <summary>
    /// 背景音乐编号
    /// </summary>
    public int BackgroundMusicId { get; private set; }

    public const int __ID__ = -1391422991;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AssetName:" + AssetName + ","
        + "BackgroundMusicId:" + BackgroundMusicId + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
