//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Game.Hotfix.Cfg.Item
{

public sealed partial class Sound :  Bright.Config.BeanBase 
{
    public Sound(JSONNode _json) 
    {
        { if(!_json["Id"].IsNumber) { throw new SerializationException(); }  Id = _json["Id"]; }
        { if(!_json["AssetName"].IsString) { throw new SerializationException(); }  AssetName = _json["AssetName"]; }
        { if(!_json["Priority"].IsNumber) { throw new SerializationException(); }  Priority = _json["Priority"]; }
        { if(!_json["Loop"].IsBoolean) { throw new SerializationException(); }  Loop = _json["Loop"]; }
        { if(!_json["Volume"].IsNumber) { throw new SerializationException(); }  Volume = _json["Volume"]; }
        { if(!_json["SpatialBlend"].IsNumber) { throw new SerializationException(); }  SpatialBlend = _json["SpatialBlend"]; }
        { if(!_json["MaxDistance"].IsNumber) { throw new SerializationException(); }  MaxDistance = _json["MaxDistance"]; }
        PostInit();
    }

    public Sound(int Id, string AssetName, int Priority, bool Loop, float Volume, float SpatialBlend, float MaxDistance ) 
    {
        this.Id = Id;
        this.AssetName = AssetName;
        this.Priority = Priority;
        this.Loop = Loop;
        this.Volume = Volume;
        this.SpatialBlend = SpatialBlend;
        this.MaxDistance = MaxDistance;
        PostInit();
    }

    public static Sound DeserializeSound(JSONNode _json)
    {
        return new Item.Sound(_json);
    }

    /// <summary>
    /// 声音编号
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 资源名称
    /// </summary>
    public string AssetName { get; private set; }
    /// <summary>
    /// 优先级（默认0，128最高，-128最低）
    /// </summary>
    public int Priority { get; private set; }
    /// <summary>
    /// 是否循环
    /// </summary>
    public bool Loop { get; private set; }
    /// <summary>
    /// 音量（0~1）
    /// </summary>
    public float Volume { get; private set; }
    /// <summary>
    /// 声音空间混合量（0为2D，1为3D，中间值混合效果）
    /// </summary>
    public float SpatialBlend { get; private set; }
    /// <summary>
    /// 声音最大距离
    /// </summary>
    public float MaxDistance { get; private set; }

    public const int __ID__ = -1391050124;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AssetName:" + AssetName + ","
        + "Priority:" + Priority + ","
        + "Loop:" + Loop + ","
        + "Volume:" + Volume + ","
        + "SpatialBlend:" + SpatialBlend + ","
        + "MaxDistance:" + MaxDistance + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
