//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Game.Hotfix.Cfg.Item
{

public sealed partial class UISound :  Bright.Config.BeanBase 
{
    public UISound(JSONNode _json) 
    {
        { if(!_json["Id"].IsNumber) { throw new SerializationException(); }  Id = _json["Id"]; }
        { if(!_json["AssetName"].IsString) { throw new SerializationException(); }  AssetName = _json["AssetName"]; }
        { if(!_json["Priority"].IsNumber) { throw new SerializationException(); }  Priority = _json["Priority"]; }
        { if(!_json["Volume"].IsNumber) { throw new SerializationException(); }  Volume = _json["Volume"]; }
        PostInit();
    }

    public UISound(int Id, string AssetName, int Priority, float Volume ) 
    {
        this.Id = Id;
        this.AssetName = AssetName;
        this.Priority = Priority;
        this.Volume = Volume;
        PostInit();
    }

    public static UISound DeserializeUISound(JSONNode _json)
    {
        return new Item.UISound(_json);
    }

    /// <summary>
    /// 声音编号
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 资源名称
    /// </summary>
    public string AssetName { get; private set; }
    /// <summary>
    /// 优先级（默认0，128最高，-128最低）
    /// </summary>
    public int Priority { get; private set; }
    /// <summary>
    /// 音量（0~1）
    /// </summary>
    public float Volume { get; private set; }

    public const int __ID__ = -408590560;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AssetName:" + AssetName + ","
        + "Priority:" + Priority + ","
        + "Volume:" + Volume + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
