//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Hotfix.Cfg
{
    /// <summary>
    /// 实体类型
    /// </summary>
    [System.Flags]
    public enum EntityType
    {
        /// <summary>
        /// 非玩家角色
        /// </summary>
        NPC = 1,
        /// <summary>
        /// 怪物
        /// </summary>
        Monster = 2,
        /// <summary>
        /// 智体
        /// </summary>
        AI = NPC|Monster,
    }
}
