//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;
using System.Threading.Tasks;
using Game;


namespace Game.Hotfix.Cfg
{
   
public sealed partial class Tables : BaseLubanTables
{
    public TbEntity TbEntity {get; private set; }
    public TbMusic TbMusic {get; private set; }
    public TbScene TbScene {get; private set; }
    public TbSound TbSound {get; private set; }
    public TbUIForm TbUIForm {get; private set; }
    public TbUISound TbUISound {get; private set; }

    public Tables() { }
	
	public override LubanTableType GetTableType
    {
        get { return LubanTableType.JSON; }
    }
    
    public override async Task LoadAsync(System.Func<string, Task<JSONNode>> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbEntity = new TbEntity(await loader("tbentity")); 
        tables.Add("TbEntity", TbEntity);
        TbMusic = new TbMusic(await loader("tbmusic")); 
        tables.Add("TbMusic", TbMusic);
        TbScene = new TbScene(await loader("tbscene")); 
        tables.Add("TbScene", TbScene);
        TbSound = new TbSound(await loader("tbsound")); 
        tables.Add("TbSound", TbSound);
        TbUIForm = new TbUIForm(await loader("tbuiform")); 
        tables.Add("TbUIForm", TbUIForm);
        TbUISound = new TbUISound(await loader("tbuisound")); 
        tables.Add("TbUISound", TbUISound);

        TbEntity.Resolve(tables); 
        TbMusic.Resolve(tables); 
        TbScene.Resolve(tables); 
        TbSound.Resolve(tables); 
        TbUIForm.Resolve(tables); 
        TbUISound.Resolve(tables); 
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        TbEntity.TranslateText(translator); 
        TbMusic.TranslateText(translator); 
        TbScene.TranslateText(translator); 
        TbSound.TranslateText(translator); 
        TbUIForm.TranslateText(translator); 
        TbUISound.TranslateText(translator); 
    }
}

}