//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Game.Hotfix.Cfg
{

public sealed partial class TbEntity
{
    private readonly Dictionary<int, Item.Entity> _dataMap;
    private readonly List<Item.Entity> _dataList;
    
    public TbEntity(JSONNode _json)
    {
        _dataMap = new Dictionary<int, Item.Entity>();
        _dataList = new List<Item.Entity>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = Item.Entity.DeserializeEntity(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Item.Entity> DataMap => _dataMap;
    public List<Item.Entity> DataList => _dataList;

    public Item.Entity GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Item.Entity Get(int key) => _dataMap[key];
    public Item.Entity this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}